# Absolute path is recommended since the location
# sqlite3 is being run can change.
# For example generation time and model test time.
[sqlite3]
dbname = "database.sqlite3"
blacklist = ["schema_migrations"]